#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  8 09:50:43 2020

@author: Cheerag
"""

def nearestGreaterToRight(arr):
    '''
    arr[]  :  3 7 6  9 10
    result : -1 3 7 -1 -1
    '''
    stack  = []
    result = []
    for ele in range(len(arr)):
        if len(stack) == 0:
            result.append(-1)
            stack.append(arr[ele])
        
        elif stack is not None:
            while len(stack)>0 and arr[ele] > stack[-1] :
                stack.pop()
                
            if len(stack) == 0:
                result.append(-1)
                stack.append(arr[ele])   
            
            elif arr[ele] < stack[-1]:
                result.append(stack[-1])
                stack.append(arr[ele])
                
    return result

arr = list(map(int,input().split()))
print(nearestGreaterToRight(arr))
