#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  7 17:02:00 2020

@author: Cheerag
"""


def nearestGreaterToRight(arr):
    if len(arr) == 0:
        return 0
    stack  = []
    result = []
    for ele in range(len(arr)-1,-1,-1):
        if len(stack) == 0:
            result.append(-1)
            stack.append(arr[ele])
        
        elif stack is not None:
            while arr[ele] > stack[-1]:
                stack.pop()
            
            if arr[ele] < stack[-1]:
                result.append(stack[-1])
                stack.append(arr[ele])
                
    return result

#arr = list(map(int,input().split()))
arr = [1,3,2,4]
reversedArr = nearestGreaterToRight(arr)
print(reversedArr[::-1])